server:
  port: 8110 # 服务端口

spring:
  profiles:
    active: dev # 环境设置 设置为开发环境
  application:
    name: service-core # 服务名
  datasource: # mysql数据库连接
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/finance_core?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 12345678

mybatis-plus: #mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # mybatis日志输出
  mapper-locations: classpath:com/lee/financeplatform/core/mapper/xml/*.xml # mybatis xml文件的位置

#  #  设置日志级别
#logging:
#  level:
#    root: ERROR
